//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.PayRollAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_Emp_PF_Contribution
    {
        public int PF_ContributionId { get; set; }
        public string EID { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<decimal> Employer_PF_Contribution { get; set; }
        public Nullable<decimal> Employee_PF_Contribution { get; set; }
        public Nullable<decimal> PF_Loan_Amount { get; set; }
        public Nullable<decimal> PF_Loan_Interest { get; set; }
        public Nullable<int> PF_Month { get; set; }
        public Nullable<int> PF_Year { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public string OCode { get; set; }
    }
}
