//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.PayRollAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_SECTIONS
    {
        public int SEC_ID { get; set; }
        public string SEC_NAME { get; set; }
        public Nullable<int> DPT_ID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<System.Guid> EDIT_USER { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string OCODE { get; set; }
    }
}
