//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL.PayRollAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PREntities : DbContext
    {
        public PREntities()
            : base("name=PREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HRM_DEPARTMENTS> HRM_DEPARTMENTS { get; set; }
        public DbSet<HRM_DESIGNATIONS> HRM_DESIGNATIONS { get; set; }
        public DbSet<HRM_Emp_PF_Contribution> HRM_Emp_PF_Contribution { get; set; }
        public DbSet<HRM_PersonalInformations> HRM_PersonalInformations { get; set; }
        public DbSet<HRM_SECTIONS> HRM_SECTIONS { get; set; }
    }
}
