//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_VoucherDetail
    {
        public System.Guid VoucherDetailID { get; set; }
        public int VoucherID { get; set; }
        public System.Guid LedgerID { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> VTypeID { get; set; }
        public string EditUserName { get; set; }
        public Nullable<int> PFMemberID { get; set; }
        public string PFAdditionalInformation { get; set; }
        public Nullable<int> OCode { get; set; }
        public string PFLoanID { get; set; }
    
        public virtual acc_Ledger acc_Ledger { get; set; }
        public virtual acc_VoucherDetail acc_VoucherDetail1 { get; set; }
        public virtual acc_VoucherDetail acc_VoucherDetail2 { get; set; }
        public virtual acc_VoucherEntry acc_VoucherEntry { get; set; }
    }
}
