//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_Group
    {
        public acc_Group()
        {
            this.acc_Group1 = new HashSet<acc_Group>();
            this.acc_Ledger = new HashSet<acc_Ledger>();
        }
    
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ParentGroupID { get; set; }
        public Nullable<int> NatureID { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public Nullable<bool> RestrictDelete { get; set; }
        public string EditUserName { get; set; }
        public Nullable<bool> IsSystemDefault { get; set; }
        public Nullable<int> OCode { get; set; }
        public string GroupCode { get; set; }
    
        public virtual ICollection<acc_Group> acc_Group1 { get; set; }
        public virtual acc_Group acc_Group2 { get; set; }
        public virtual ICollection<acc_Ledger> acc_Ledger { get; set; }
    }
}
