//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_tbl_PFRules
    {
        public int ROWID { get; set; }
        public int WorkingDurationInMonth { get; set; }
        public decimal EmployeeContribution { get; set; }
        public decimal EmployerContribution { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
        public byte IsActive { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public string RuleName { get; set; }
        public Nullable<int> OCode { get; set; }
    }
}
