//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_tbl_Branch
    {
        public LU_tbl_Branch()
        {
            this.tbl_Employees = new HashSet<tbl_Employees>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public string BranchLocation { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
        public Nullable<int> OCode { get; set; }
        public string EditUserName { get; set; }
    
        public virtual ICollection<tbl_Employees> tbl_Employees { get; set; }
    }
}
