//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_tbl_District
    {
        public string DistrictID { get; set; }
        public string DistrictName { get; set; }
        public string CountryID { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
        public Nullable<int> OCode { get; set; }
    
        public virtual LU_tbl_Country LU_tbl_Country { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
