//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_Contribution
    {
        public int EmpID { get; set; }
        public string ConYear { get; set; }
        public string ConMonth { get; set; }
        public decimal SelfContribution { get; set; }
        public Nullable<decimal> SCInterest { get; set; }
        public decimal EmpContribution { get; set; }
        public Nullable<decimal> ECInterest { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
        public int PFRulesID { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> SCPercentage { get; set; }
        public Nullable<decimal> ECPercentage { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<int> ProcessID { get; set; }
    
        public virtual PF_Employees PF_Employees { get; set; }
        public virtual User_Detail User_Detail { get; set; }
    }
}
