//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_Country
    {
        public PF_Country()
        {
            this.PF_District = new HashSet<PF_District>();
        }
    
        public string CountryID { get; set; }
        public string CountryName { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
    
        public virtual User_Detail User_Detail { get; set; }
        public virtual ICollection<PF_District> PF_District { get; set; }
    }
}
