//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_CompanyInformation
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public Nullable<System.DateTime> SystemImplementationDate { get; set; }
        public Nullable<System.DateTime> AccountingYearBeginningFrom { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public string EditUserName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
