//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_Department
    {
        public PF_Department()
        {
            this.PF_Employees = new HashSet<PF_Employees>();
        }
    
        public string DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
    
        public virtual User_Detail User_Detail { get; set; }
        public virtual ICollection<PF_Employees> PF_Employees { get; set; }
    }
}
