//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_Employees
    {
        public PF_Employees()
        {
            this.PF_Amortization = new HashSet<PF_Amortization>();
            this.PF_Contribution = new HashSet<PF_Contribution>();
        }
    
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Branch { get; set; }
        public string Gender { get; set; }
        public string PresentAddress { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string NID { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> PFStatus { get; set; }
        public string EmpImg { get; set; }
        public string SignatureImg { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
        public string IdentificationNumber { get; set; }
        public Nullable<decimal> opOwnContribution { get; set; }
        public Nullable<decimal> opEmpContribution { get; set; }
        public Nullable<decimal> opProfit { get; set; }
        public Nullable<decimal> opLoan { get; set; }
        public string opDesignationName { get; set; }
        public string opDepartmentName { get; set; }
        public System.DateTime PFActivationDate { get; set; }
        public Nullable<System.DateTime> PFDeactivationDate { get; set; }
        public Nullable<System.Guid> PFDeactivatedBy { get; set; }
        public string PFDeactivatedByName { get; set; }
        public string EditUserName { get; set; }
        public string Comment { get; set; }
        public Nullable<int> PFRuleUsedForDeactivation { get; set; }
        public bool PassVoucher { get; set; }
        public string PassVoucherMessage { get; set; }
    
        public virtual ICollection<PF_Amortization> PF_Amortization { get; set; }
        public virtual PF_Branch PF_Branch { get; set; }
        public virtual ICollection<PF_Contribution> PF_Contribution { get; set; }
        public virtual PF_Department PF_Department { get; set; }
        public virtual PF_Designation PF_Designation { get; set; }
        public virtual PF_PFStatus PF_PFStatus { get; set; }
        public virtual User_Detail User_Detail { get; set; }
    }
}
