//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_Instrument
    {
        public int InstrumentID { get; set; }
        public string InstrumentType { get; set; }
        public string InstrumentNumber { get; set; }
        public string Institution { get; set; }
        public string Branch { get; set; }
        public System.DateTime DepositDate { get; set; }
        public int MaturityPeriod { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public decimal Amount { get; set; }
        public decimal InterestRate { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public string EditUserName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string Comment { get; set; }
        public bool PassVoucher { get; set; }
        public string PassVoucherMessage { get; set; }
        public Nullable<System.Guid> AccLedgerID { get; set; }
    }
}
