//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_Loan
    {
        public int EmpID { get; set; }
        public string PFLoanID { get; set; }
        public decimal LoanAmount { get; set; }
        public Nullable<int> TermYear { get; set; }
        public int TermMonth { get; set; }
        public decimal Interest { get; set; }
        public decimal Installment { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
        public byte IsApproved { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public string EditUserName { get; set; }
    }
}
