//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_MembershipClosingRules
    {
        public int ROWID { get; set; }
        public int PFDurationInMonth { get; set; }
        public bool OwnPartPayable { get; set; }
        public bool EmployerPartPayable { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
        public byte IsActive { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public string RuleName { get; set; }
        public bool ProfitPartPayable { get; set; }
    }
}
