//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PFTMEntities : DbContext
    {
        public PFTMEntities()
            : base("name=PFTMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ac_Cheque_BankInfo> Ac_Cheque_BankInfo { get; set; }
        public DbSet<Ac_Cheque_ClientInfo> Ac_Cheque_ClientInfo { get; set; }
        public DbSet<acc_Chart_of_Account_Maping> acc_Chart_of_Account_Maping { get; set; }
        public DbSet<acc_Group> acc_Group { get; set; }
        public DbSet<acc_Ledger> acc_Ledger { get; set; }
        public DbSet<acc_Nature> acc_Nature { get; set; }
        public DbSet<acc_tbl_MIS> acc_tbl_MIS { get; set; }
        public DbSet<acc_VoucherDetail> acc_VoucherDetail { get; set; }
        public DbSet<acc_VoucherEntry> acc_VoucherEntry { get; set; }
        public DbSet<acc_VoucherType> acc_VoucherType { get; set; }
        public DbSet<LU_tbl_Branch> LU_tbl_Branch { get; set; }
        public DbSet<LU_tbl_CompanyInformation> LU_tbl_CompanyInformation { get; set; }
        public DbSet<LU_tbl_Country> LU_tbl_Country { get; set; }
        public DbSet<LU_tbl_Department> LU_tbl_Department { get; set; }
        public DbSet<LU_tbl_Designation> LU_tbl_Designation { get; set; }
        public DbSet<LU_tbl_District> LU_tbl_District { get; set; }
        public DbSet<LU_tbl_LoanRules> LU_tbl_LoanRules { get; set; }
        public DbSet<LU_tbl_MembershipClosingRules> LU_tbl_MembershipClosingRules { get; set; }
        public DbSet<LU_tbl_PFRules> LU_tbl_PFRules { get; set; }
        public DbSet<SA_tbl_Module> SA_tbl_Module { get; set; }
        public DbSet<SA_tbl_Page> SA_tbl_Page { get; set; }
        public DbSet<SA_tbl_PagePermission> SA_tbl_PagePermission { get; set; }
        public DbSet<tbl_Contribution> tbl_Contribution { get; set; }
        public DbSet<tbl_ContributionMonthRecord> tbl_ContributionMonthRecord { get; set; }
        public DbSet<tbl_Employees> tbl_Employees { get; set; }
        public DbSet<tbl_ErrorLog> tbl_ErrorLog { get; set; }
        public DbSet<tbl_FinancialAuditLog> tbl_FinancialAuditLog { get; set; }
        public DbSet<tbl_LoginHistory> tbl_LoginHistory { get; set; }
        public DbSet<tbl_NomineeInformation> tbl_NomineeInformation { get; set; }
        public DbSet<tbl_PFL_Amortization> tbl_PFL_Amortization { get; set; }
        public DbSet<tbl_PFLoan> tbl_PFLoan { get; set; }
        public DbSet<tbl_ProfitDistributionSummary> tbl_ProfitDistributionSummary { get; set; }
        public DbSet<tbl_User> tbl_User { get; set; }
        public DbSet<tbl_UserPassword> tbl_UserPassword { get; set; }
        public DbSet<tbl_UserRedirected> tbl_UserRedirected { get; set; }
        public DbSet<tbl_UserRole> tbl_UserRole { get; set; }
        public DbSet<Ac_Cheque_Print> Ac_Cheque_Print { get; set; }
        public DbSet<tbl_ProfitDistributionDetail> tbl_ProfitDistributionDetail { get; set; }
        public DbSet<tbl_Instrument> tbl_Instrument { get; set; }
        public DbSet<acc_Group_Maping> acc_Group_Maping { get; set; }
        public DbSet<acc_tbl_Group_MIS> acc_tbl_Group_MIS { get; set; }
        public DbSet<tbl_Instrument_Accured_Interest> tbl_Instrument_Accured_Interest { get; set; }
        public DbSet<tbl_Instrument_Interest_Rate> tbl_Instrument_Interest_Rate { get; set; }
    }
}
