//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public tbl_User()
        {
            this.LU_tbl_Country = new HashSet<LU_tbl_Country>();
            this.LU_tbl_Department = new HashSet<LU_tbl_Department>();
            this.LU_tbl_Designation = new HashSet<LU_tbl_Designation>();
            this.LU_tbl_District = new HashSet<LU_tbl_District>();
            this.tbl_Contribution = new HashSet<tbl_Contribution>();
            this.tbl_Employees = new HashSet<tbl_Employees>();
            this.tbl_PFL_Amortization = new HashSet<tbl_PFL_Amortization>();
        }
    
        public System.Guid UserID { get; set; }
        public string LoginName { get; set; }
        public string UserFullName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public byte IsActive { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
        public string Phone { get; set; }
        public Nullable<byte> EmailNotificationActive { get; set; }
        public string Email { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> OCode { get; set; }
    
        public virtual ICollection<LU_tbl_Country> LU_tbl_Country { get; set; }
        public virtual ICollection<LU_tbl_Department> LU_tbl_Department { get; set; }
        public virtual ICollection<LU_tbl_Designation> LU_tbl_Designation { get; set; }
        public virtual ICollection<LU_tbl_District> LU_tbl_District { get; set; }
        public virtual ICollection<tbl_Contribution> tbl_Contribution { get; set; }
        public virtual ICollection<tbl_Employees> tbl_Employees { get; set; }
        public virtual ICollection<tbl_PFL_Amortization> tbl_PFL_Amortization { get; set; }
    }
}
