//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProfitDistributionSummary
    {
        public int ProcessID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> DistributableAmount { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public string EditUserName { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string Message { get; set; }
        public Nullable<int> OCode { get; set; }
        public Nullable<decimal> DistributedAmount { get; set; }
        public Nullable<decimal> SelfTotalProfit { get; set; }
        public Nullable<decimal> EmpTotalProfit { get; set; }
    }
}
