//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContributionMonthRecord
    {
        public int ID { get; set; }
        public string ConYear { get; set; }
        public string ConMonth { get; set; }
        public bool PassVoucher { get; set; }
        public string PassVoucherMessage { get; set; }
        public System.Guid EditUser { get; set; }
        public string EditUserName { get; set; }
        public System.DateTime EditDate { get; set; }
        public Nullable<decimal> TotalSelfCont { get; set; }
        public Nullable<decimal> TotalEmpCont { get; set; }
        public Nullable<int> OCode { get; set; }
        public Nullable<System.DateTime> ContributionDate { get; set; }
    }
}
