//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Instrument
    {
        public int InstrumentID { get; set; }
        public string InstrumentType { get; set; }
        public string InstrumentNumber { get; set; }
        public string Institution { get; set; }
        public string Branch { get; set; }
        public System.DateTime DepositDate { get; set; }
        public int MaturityPeriod { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public decimal Amount { get; set; }
        public decimal InterestRate { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public string EditUserName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string Comment { get; set; }
        public bool PassVoucher { get; set; }
        public string PassVoucherMessage { get; set; }
        public Nullable<System.Guid> AccLedgerID { get; set; }
        public Nullable<int> OCode { get; set; }
        public Nullable<int> AccVoucherEntryID { get; set; }
        public string InstrumentPhoto { get; set; }
        public Nullable<bool> Closed { get; set; }
        public decimal AcruadIntarestAmount { get; set; }
        public string EntryForPF { get; set; }
        public string EntryForGF { get; set; }
        public string EntryForWPPF { get; set; }
        public Nullable<decimal> BankCharge { get; set; }
        public Nullable<decimal> TDSonFDR { get; set; }
        public Nullable<decimal> FDRTax { get; set; }
        public Nullable<System.DateTime> LastProcessDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> PreviousInstrumentId { get; set; }
    }
}
