//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ErrorLog
    {
        public int ID { get; set; }
        public string Message { get; set; }
        public string InnerException { get; set; }
        public string UserName { get; set; }
        public string Terminal { get; set; }
        public string HostName { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Type { get; set; }
        public Nullable<int> OCode { get; set; }
    }
}
