//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_tbl_ProfitDistributionDetail
    {
        public int EmpID { get; set; }
        public string IdentificationNumber { get; set; }
        public int ProcessID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> DistributedAmount { get; set; }
        public Nullable<int> OCode { get; set; }
        public decimal SelfContribution { get; set; }
    }
}
