//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Detail
    {
        public User_Detail()
        {
            this.PF_Amortization = new HashSet<PF_Amortization>();
            this.PF_Contribution = new HashSet<PF_Contribution>();
            this.PF_Country = new HashSet<PF_Country>();
            this.PF_Department = new HashSet<PF_Department>();
            this.PF_Designation = new HashSet<PF_Designation>();
            this.PF_District = new HashSet<PF_District>();
            this.PF_Employees = new HashSet<PF_Employees>();
            this.PF_PFStatus = new HashSet<PF_PFStatus>();
        }
    
        public System.Guid UserID { get; set; }
        public string LoginName { get; set; }
        public string UserFullName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string BranchID { get; set; }
        public byte IsActive { get; set; }
        public System.Guid EditUser { get; set; }
        public System.DateTime EditDate { get; set; }
        public string Phone { get; set; }
        public Nullable<byte> EmailNotificationActive { get; set; }
        public string Email { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<int> EmpID { get; set; }
    
        public virtual ICollection<PF_Amortization> PF_Amortization { get; set; }
        public virtual ICollection<PF_Contribution> PF_Contribution { get; set; }
        public virtual ICollection<PF_Country> PF_Country { get; set; }
        public virtual ICollection<PF_Department> PF_Department { get; set; }
        public virtual ICollection<PF_Designation> PF_Designation { get; set; }
        public virtual ICollection<PF_District> PF_District { get; set; }
        public virtual ICollection<PF_Employees> PF_Employees { get; set; }
        public virtual ICollection<PF_PFStatus> PF_PFStatus { get; set; }
    }
}
